<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operation.proto

namespace Yandex\Cloud\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Operation is annotation for rpc that returns longrunning operation, describes
 * message types that will be returned in metadata [google.protobuf.Any], and
 * in response [google.protobuf.Any] (for successful operation).
 *
 * Generated from protobuf message <code>yandex.cloud.api.Operation</code>
 */
class Operation extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional. If present, rpc returns operation which metadata field will
     * contains message of specified type.
     *
     * Generated from protobuf field <code>string metadata = 1;</code>
     */
    protected $metadata = '';
    /**
     * Required. rpc returns operation, in case of success response will contains message of
     * specified field.
     *
     * Generated from protobuf field <code>string response = 2;</code>
     */
    protected $response = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $metadata
     *           Optional. If present, rpc returns operation which metadata field will
     *           contains message of specified type.
     *     @type string $response
     *           Required. rpc returns operation, in case of success response will contains message of
     *           specified field.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Operation::initOnce();
        parent::__construct($data);
    }

    /**
     * Optional. If present, rpc returns operation which metadata field will
     * contains message of specified type.
     *
     * Generated from protobuf field <code>string metadata = 1;</code>
     * @return string
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Optional. If present, rpc returns operation which metadata field will
     * contains message of specified type.
     *
     * Generated from protobuf field <code>string metadata = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkString($var, True);
        $this->metadata = $var;

        return $this;
    }

    /**
     * Required. rpc returns operation, in case of success response will contains message of
     * specified field.
     *
     * Generated from protobuf field <code>string response = 2;</code>
     * @return string
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Required. rpc returns operation, in case of success response will contains message of
     * specified field.
     *
     * Generated from protobuf field <code>string response = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkString($var, True);
        $this->response = $var;

        return $this;
    }

}

