<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_service.proto

namespace Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingPairParams;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>yandex.cloud.ai.tuning.v1.TextEmbeddingPairParams.Optimizer</code>
 */
class Optimizer extends \Google\Protobuf\Internal\Message
{
    protected $type;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Yandex\Cloud\Ai\Tuning\V1\OptimizerAdamw $adamw
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yandex\Cloud\Ai\Tuning\V1\TuningService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.OptimizerAdamw adamw = 1;</code>
     * @return \Yandex\Cloud\Ai\Tuning\V1\OptimizerAdamw|null
     */
    public function getAdamw()
    {
        return $this->readOneof(1);
    }

    public function hasAdamw()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.OptimizerAdamw adamw = 1;</code>
     * @param \Yandex\Cloud\Ai\Tuning\V1\OptimizerAdamw $var
     * @return $this
     */
    public function setAdamw($var)
    {
        GPBUtil::checkMessage($var, \Yandex\Cloud\Ai\Tuning\V1\OptimizerAdamw::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getType()
    {
        return $this->whichOneof("type");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Optimizer::class, \Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingPairParams_Optimizer::class);

