<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/validation.proto

namespace Yandex\Cloud;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>yandex.cloud.MapKeySpec</code>
 */
class MapKeySpec extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string value = 1;</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>string pattern = 2;</code>
     */
    protected $pattern = '';
    /**
     * Generated from protobuf field <code>string length = 3;</code>
     */
    protected $length = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $value
     *     @type string $pattern
     *     @type string $length
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yandex\Cloud\Validation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string value = 1;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pattern = 2;</code>
     * @return string
     */
    public function getPattern()
    {
        return $this->pattern;
    }

    /**
     * Generated from protobuf field <code>string pattern = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPattern($var)
    {
        GPBUtil::checkString($var, True);
        $this->pattern = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string length = 3;</code>
     * @return string
     */
    public function getLength()
    {
        return $this->length;
    }

    /**
     * Generated from protobuf field <code>string length = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLength($var)
    {
        GPBUtil::checkString($var, True);
        $this->length = $var;

        return $this;
    }

}

