<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/operation/operation_service.proto

namespace GPBMetadata\Yandex\Cloud\Operation;

class OperationService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Yandex\Cloud\Operation\Operation::initOnce();
        \GPBMetadata\Yandex\Cloud\Validation::initOnce();
        $pool->internalAddGeneratedFile(
            '
˝
.yandex/cloud/operation/operation_service.protoyandex.cloud.operation&yandex/cloud/operation/operation.protoyandex/cloud/validation.proto"1
GetOperationRequest
operation_id (	BË«1"4
CancelOperationRequest
operation_id (	BË«12ñ
OperationServicey
Get+.yandex.cloud.operation.GetOperationRequest!.yandex.cloud.operation.Operation""Ç”‰ì/operations/{operation_id}Ü
Cancel..yandex.cloud.operation.CancelOperationRequest!.yandex.cloud.operation.Operation")Ç”‰ì#!/operations/{operation_id}:cancelBb
yandex.cloud.api.operationZDgithub.com/yandex-cloud/go-genproto/yandex/cloud/operation;operationbproto3'
        , true);

        static::$is_initialized = true;
    }
}

