<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/api/operation.proto

namespace GPBMetadata\Yandex\Cloud\Api\Operation;

class Operation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ë
 yandex/cloud/api/operation.protoyandex.cloud.api google/protobuf/descriptor.proto"/
	Operation
metadata (	
response (	B:Z8github.com/yandex-cloud/go-genproto/yandex/cloud/api;apibproto3'
        , true);

        static::$is_initialized = true;
    }
}

