<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/validation.proto

namespace GPBMetadata\Yandex\Cloud;

class Validation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
á
yandex/cloud/validation.protoyandex.cloud google/protobuf/descriptor.proto"<

MapKeySpec
value (	
pattern (	
length (	BJ
yandex.cloud.apiZ6github.com/yandex-cloud/go-genproto/yandex/cloud;cloudbproto3'
        , true);

        static::$is_initialized = true;
    }
}

