<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/operation/operation_service.proto

namespace Yandex\Cloud\Operation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>yandex.cloud.operation.GetOperationRequest</code>
 */
class GetOperationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * ID of the Operation resource to return.
     *
     * Generated from protobuf field <code>string operation_id = 1 [(.yandex.cloud.required) = true];</code>
     */
    protected $operation_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $operation_id
     *           ID of the Operation resource to return.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yandex\Cloud\Operation\OperationService::initOnce();
        parent::__construct($data);
    }

    /**
     * ID of the Operation resource to return.
     *
     * Generated from protobuf field <code>string operation_id = 1 [(.yandex.cloud.required) = true];</code>
     * @return string
     */
    public function getOperationId()
    {
        return $this->operation_id;
    }

    /**
     * ID of the Operation resource to return.
     *
     * Generated from protobuf field <code>string operation_id = 1 [(.yandex.cloud.required) = true];</code>
     * @param string $var
     * @return $this
     */
    public function setOperationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->operation_id = $var;

        return $this;
    }

}

