<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/operation/operation.proto

namespace Yandex\Cloud\Operation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * An Operation resource. For more information, see [Operation](/docs/api-design-guide/concepts/operation).
 *
 * Generated from protobuf message <code>yandex.cloud.operation.Operation</code>
 */
class Operation extends \Google\Protobuf\Internal\Message
{
    /**
     * ID of the operation.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Description of the operation. 0-256 characters long.
     *
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * Creation timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 3;</code>
     */
    protected $created_at = null;
    /**
     * ID of the user or service account who initiated the operation.
     *
     * Generated from protobuf field <code>string created_by = 4;</code>
     */
    protected $created_by = '';
    /**
     * The time when the Operation resource was last modified.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp modified_at = 5;</code>
     */
    protected $modified_at = null;
    /**
     * If the value is `false`, it means the operation is still in progress.
     * If `true`, the operation is completed, and either `error` or `response` is available.
     *
     * Generated from protobuf field <code>bool done = 6;</code>
     */
    protected $done = false;
    /**
     * Service-specific metadata associated with the operation.
     * It typically contains the ID of the target resource that the operation is performed on.
     * Any method that returns a long-running operation should document the metadata type, if any.
     *
     * Generated from protobuf field <code>.google.protobuf.Any metadata = 7;</code>
     */
    protected $metadata = null;
    protected $result;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           ID of the operation.
     *     @type string $description
     *           Description of the operation. 0-256 characters long.
     *     @type \Google\Protobuf\Timestamp $created_at
     *           Creation timestamp.
     *     @type string $created_by
     *           ID of the user or service account who initiated the operation.
     *     @type \Google\Protobuf\Timestamp $modified_at
     *           The time when the Operation resource was last modified.
     *     @type bool $done
     *           If the value is `false`, it means the operation is still in progress.
     *           If `true`, the operation is completed, and either `error` or `response` is available.
     *     @type \Google\Protobuf\Any $metadata
     *           Service-specific metadata associated with the operation.
     *           It typically contains the ID of the target resource that the operation is performed on.
     *           Any method that returns a long-running operation should document the metadata type, if any.
     *     @type \Google\Rpc\Status $error
     *           The error result of the operation in case of failure or cancellation.
     *     @type \Google\Protobuf\Any $response
     *           The normal response of the operation in case of success.
     *           If the original method returns no data on success, such as Delete,
     *           the response is [google.protobuf.Empty].
     *           If the original method is the standard Create/Update,
     *           the response should be the target resource of the operation.
     *           Any method that returns a long-running operation should document the response type, if any.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yandex\Cloud\Operation\Operation::initOnce();
        parent::__construct($data);
    }

    /**
     * ID of the operation.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * ID of the operation.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Description of the operation. 0-256 characters long.
     *
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Description of the operation. 0-256 characters long.
     *
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Creation timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 3;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Creation timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * ID of the user or service account who initiated the operation.
     *
     * Generated from protobuf field <code>string created_by = 4;</code>
     * @return string
     */
    public function getCreatedBy()
    {
        return $this->created_by;
    }

    /**
     * ID of the user or service account who initiated the operation.
     *
     * Generated from protobuf field <code>string created_by = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedBy($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_by = $var;

        return $this;
    }

    /**
     * The time when the Operation resource was last modified.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp modified_at = 5;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getModifiedAt()
    {
        return $this->modified_at;
    }

    public function hasModifiedAt()
    {
        return isset($this->modified_at);
    }

    public function clearModifiedAt()
    {
        unset($this->modified_at);
    }

    /**
     * The time when the Operation resource was last modified.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp modified_at = 5;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setModifiedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->modified_at = $var;

        return $this;
    }

    /**
     * If the value is `false`, it means the operation is still in progress.
     * If `true`, the operation is completed, and either `error` or `response` is available.
     *
     * Generated from protobuf field <code>bool done = 6;</code>
     * @return bool
     */
    public function getDone()
    {
        return $this->done;
    }

    /**
     * If the value is `false`, it means the operation is still in progress.
     * If `true`, the operation is completed, and either `error` or `response` is available.
     *
     * Generated from protobuf field <code>bool done = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setDone($var)
    {
        GPBUtil::checkBool($var);
        $this->done = $var;

        return $this;
    }

    /**
     * Service-specific metadata associated with the operation.
     * It typically contains the ID of the target resource that the operation is performed on.
     * Any method that returns a long-running operation should document the metadata type, if any.
     *
     * Generated from protobuf field <code>.google.protobuf.Any metadata = 7;</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    public function hasMetadata()
    {
        return isset($this->metadata);
    }

    public function clearMetadata()
    {
        unset($this->metadata);
    }

    /**
     * Service-specific metadata associated with the operation.
     * It typically contains the ID of the target resource that the operation is performed on.
     * Any method that returns a long-running operation should document the metadata type, if any.
     *
     * Generated from protobuf field <code>.google.protobuf.Any metadata = 7;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->metadata = $var;

        return $this;
    }

    /**
     * The error result of the operation in case of failure or cancellation.
     *
     * Generated from protobuf field <code>.google.rpc.Status error = 8;</code>
     * @return \Google\Rpc\Status|null
     */
    public function getError()
    {
        return $this->readOneof(8);
    }

    public function hasError()
    {
        return $this->hasOneof(8);
    }

    /**
     * The error result of the operation in case of failure or cancellation.
     *
     * Generated from protobuf field <code>.google.rpc.Status error = 8;</code>
     * @param \Google\Rpc\Status $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Google\Rpc\Status::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * The normal response of the operation in case of success.
     * If the original method returns no data on success, such as Delete,
     * the response is [google.protobuf.Empty].
     * If the original method is the standard Create/Update,
     * the response should be the target resource of the operation.
     * Any method that returns a long-running operation should document the response type, if any.
     *
     * Generated from protobuf field <code>.google.protobuf.Any response = 9;</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getResponse()
    {
        return $this->readOneof(9);
    }

    public function hasResponse()
    {
        return $this->hasOneof(9);
    }

    /**
     * The normal response of the operation in case of success.
     * If the original method returns no data on success, such as Delete,
     * the response is [google.protobuf.Empty].
     * If the original method is the standard Create/Update,
     * the response should be the target resource of the operation.
     * Any method that returns a long-running operation should document the response type, if any.
     *
     * Generated from protobuf field <code>.google.protobuf.Any response = 9;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getResult()
    {
        return $this->whichOneof("result");
    }

}

