<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_service.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>yandex.cloud.ai.tuning.v1.DescribeTuningResponse</code>
 */
class DescribeTuningResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTask tuning_task = 1;</code>
     */
    protected $tuning_task = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Yandex\Cloud\Ai\Tuning\V1\TuningTask $tuning_task
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yandex\Cloud\Ai\Tuning\V1\TuningService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTask tuning_task = 1;</code>
     * @return \Yandex\Cloud\Ai\Tuning\V1\TuningTask|null
     */
    public function getTuningTask()
    {
        return $this->tuning_task;
    }

    public function hasTuningTask()
    {
        return isset($this->tuning_task);
    }

    public function clearTuningTask()
    {
        unset($this->tuning_task);
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTask tuning_task = 1;</code>
     * @param \Yandex\Cloud\Ai\Tuning\V1\TuningTask $var
     * @return $this
     */
    public function setTuningTask($var)
    {
        GPBUtil::checkMessage($var, \Yandex\Cloud\Ai\Tuning\V1\TuningTask::class);
        $this->tuning_task = $var;

        return $this;
    }

}

