<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_service.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>yandex.cloud.ai.tuning.v1.GetOptionsResponse</code>
 */
class GetOptionsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string task_id = 1;</code>
     */
    protected $task_id = '';
    /**
     * Generated from protobuf field <code>string base_model_uri = 2;</code>
     */
    protected $base_model_uri = '';
    /**
     * Generated from protobuf field <code>repeated .yandex.cloud.ai.tuning.v1.TuningRequest.WeightedDataset train_datasets = 3;</code>
     */
    private $train_datasets;
    /**
     * Generated from protobuf field <code>repeated .yandex.cloud.ai.tuning.v1.TuningRequest.WeightedDataset validation_datasets = 4;</code>
     */
    private $validation_datasets;
    protected $tuning_params;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $task_id
     *     @type string $base_model_uri
     *     @type array<\Yandex\Cloud\Ai\Tuning\V1\TuningRequest\WeightedDataset>|\Google\Protobuf\Internal\RepeatedField $train_datasets
     *     @type array<\Yandex\Cloud\Ai\Tuning\V1\TuningRequest\WeightedDataset>|\Google\Protobuf\Internal\RepeatedField $validation_datasets
     *     @type \Yandex\Cloud\Ai\Tuning\V1\TextToTextCompletionTuningParams $text_to_text_completion
     *     @type \Yandex\Cloud\Ai\Tuning\V1\TextClassificationMultilabelParams $text_classification_multilabel
     *     @type \Yandex\Cloud\Ai\Tuning\V1\TextClassificationMulticlassParams $text_classification_multiclass
     *     @type \Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingPairParams $text_embedding_pair_params
     *     @type \Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingTripletParams $text_embedding_triplet_params
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yandex\Cloud\Ai\Tuning\V1\TuningService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string task_id = 1;</code>
     * @return string
     */
    public function getTaskId()
    {
        return $this->task_id;
    }

    /**
     * Generated from protobuf field <code>string task_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->task_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string base_model_uri = 2;</code>
     * @return string
     */
    public function getBaseModelUri()
    {
        return $this->base_model_uri;
    }

    /**
     * Generated from protobuf field <code>string base_model_uri = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBaseModelUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->base_model_uri = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .yandex.cloud.ai.tuning.v1.TuningRequest.WeightedDataset train_datasets = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTrainDatasets()
    {
        return $this->train_datasets;
    }

    /**
     * Generated from protobuf field <code>repeated .yandex.cloud.ai.tuning.v1.TuningRequest.WeightedDataset train_datasets = 3;</code>
     * @param array<\Yandex\Cloud\Ai\Tuning\V1\TuningRequest\WeightedDataset>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTrainDatasets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yandex\Cloud\Ai\Tuning\V1\TuningRequest\WeightedDataset::class);
        $this->train_datasets = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .yandex.cloud.ai.tuning.v1.TuningRequest.WeightedDataset validation_datasets = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValidationDatasets()
    {
        return $this->validation_datasets;
    }

    /**
     * Generated from protobuf field <code>repeated .yandex.cloud.ai.tuning.v1.TuningRequest.WeightedDataset validation_datasets = 4;</code>
     * @param array<\Yandex\Cloud\Ai\Tuning\V1\TuningRequest\WeightedDataset>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValidationDatasets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yandex\Cloud\Ai\Tuning\V1\TuningRequest\WeightedDataset::class);
        $this->validation_datasets = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TextToTextCompletionTuningParams text_to_text_completion = 100;</code>
     * @return \Yandex\Cloud\Ai\Tuning\V1\TextToTextCompletionTuningParams|null
     */
    public function getTextToTextCompletion()
    {
        return $this->readOneof(100);
    }

    public function hasTextToTextCompletion()
    {
        return $this->hasOneof(100);
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TextToTextCompletionTuningParams text_to_text_completion = 100;</code>
     * @param \Yandex\Cloud\Ai\Tuning\V1\TextToTextCompletionTuningParams $var
     * @return $this
     */
    public function setTextToTextCompletion($var)
    {
        GPBUtil::checkMessage($var, \Yandex\Cloud\Ai\Tuning\V1\TextToTextCompletionTuningParams::class);
        $this->writeOneof(100, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TextClassificationMultilabelParams text_classification_multilabel = 101;</code>
     * @return \Yandex\Cloud\Ai\Tuning\V1\TextClassificationMultilabelParams|null
     */
    public function getTextClassificationMultilabel()
    {
        return $this->readOneof(101);
    }

    public function hasTextClassificationMultilabel()
    {
        return $this->hasOneof(101);
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TextClassificationMultilabelParams text_classification_multilabel = 101;</code>
     * @param \Yandex\Cloud\Ai\Tuning\V1\TextClassificationMultilabelParams $var
     * @return $this
     */
    public function setTextClassificationMultilabel($var)
    {
        GPBUtil::checkMessage($var, \Yandex\Cloud\Ai\Tuning\V1\TextClassificationMultilabelParams::class);
        $this->writeOneof(101, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TextClassificationMulticlassParams text_classification_multiclass = 102;</code>
     * @return \Yandex\Cloud\Ai\Tuning\V1\TextClassificationMulticlassParams|null
     */
    public function getTextClassificationMulticlass()
    {
        return $this->readOneof(102);
    }

    public function hasTextClassificationMulticlass()
    {
        return $this->hasOneof(102);
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TextClassificationMulticlassParams text_classification_multiclass = 102;</code>
     * @param \Yandex\Cloud\Ai\Tuning\V1\TextClassificationMulticlassParams $var
     * @return $this
     */
    public function setTextClassificationMulticlass($var)
    {
        GPBUtil::checkMessage($var, \Yandex\Cloud\Ai\Tuning\V1\TextClassificationMulticlassParams::class);
        $this->writeOneof(102, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TextEmbeddingPairParams text_embedding_pair_params = 103;</code>
     * @return \Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingPairParams|null
     */
    public function getTextEmbeddingPairParams()
    {
        return $this->readOneof(103);
    }

    public function hasTextEmbeddingPairParams()
    {
        return $this->hasOneof(103);
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TextEmbeddingPairParams text_embedding_pair_params = 103;</code>
     * @param \Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingPairParams $var
     * @return $this
     */
    public function setTextEmbeddingPairParams($var)
    {
        GPBUtil::checkMessage($var, \Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingPairParams::class);
        $this->writeOneof(103, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TextEmbeddingTripletParams text_embedding_triplet_params = 104;</code>
     * @return \Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingTripletParams|null
     */
    public function getTextEmbeddingTripletParams()
    {
        return $this->readOneof(104);
    }

    public function hasTextEmbeddingTripletParams()
    {
        return $this->hasOneof(104);
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TextEmbeddingTripletParams text_embedding_triplet_params = 104;</code>
     * @param \Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingTripletParams $var
     * @return $this
     */
    public function setTextEmbeddingTripletParams($var)
    {
        GPBUtil::checkMessage($var, \Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingTripletParams::class);
        $this->writeOneof(104, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getTuningParams()
    {
        return $this->whichOneof("tuning_params");
    }

}

