<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_service.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>yandex.cloud.ai.tuning.v1.ListTuningsRequest</code>
 */
class ListTuningsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required field. ID of the folder to list tunings in.
     *
     * Generated from protobuf field <code>string folder_id = 1 [(.yandex.cloud.required) = true];</code>
     */
    protected $folder_id = '';
    /**
     * Maximum number of tuning tasks to return per page.
     *
     * Generated from protobuf field <code>int64 page_size = 2;</code>
     */
    protected $page_size = 0;
    /**
     * Token to retrieve the next page of results.
     *
     * Generated from protobuf field <code>string page_token = 3;</code>
     */
    protected $page_token = '';
    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTask.Status status = 4;</code>
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $folder_id
     *           Required field. ID of the folder to list tunings in.
     *     @type int|string $page_size
     *           Maximum number of tuning tasks to return per page.
     *     @type string $page_token
     *           Token to retrieve the next page of results.
     *     @type int $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yandex\Cloud\Ai\Tuning\V1\TuningService::initOnce();
        parent::__construct($data);
    }

    /**
     * Required field. ID of the folder to list tunings in.
     *
     * Generated from protobuf field <code>string folder_id = 1 [(.yandex.cloud.required) = true];</code>
     * @return string
     */
    public function getFolderId()
    {
        return $this->folder_id;
    }

    /**
     * Required field. ID of the folder to list tunings in.
     *
     * Generated from protobuf field <code>string folder_id = 1 [(.yandex.cloud.required) = true];</code>
     * @param string $var
     * @return $this
     */
    public function setFolderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->folder_id = $var;

        return $this;
    }

    /**
     * Maximum number of tuning tasks to return per page.
     *
     * Generated from protobuf field <code>int64 page_size = 2;</code>
     * @return int|string
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Maximum number of tuning tasks to return per page.
     *
     * Generated from protobuf field <code>int64 page_size = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * Token to retrieve the next page of results.
     *
     * Generated from protobuf field <code>string page_token = 3;</code>
     * @return string
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * Token to retrieve the next page of results.
     *
     * Generated from protobuf field <code>string page_token = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTask.Status status = 4;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTask.Status status = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Yandex\Cloud\Ai\Tuning\V1\TuningTask\Status::class);
        $this->status = $var;

        return $this;
    }

}

