<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_service.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>yandex.cloud.ai.tuning.v1.ListTuningsResponse</code>
 */
class ListTuningsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * List of tuning tasks in the specified folder.
     *
     * Generated from protobuf field <code>repeated .yandex.cloud.ai.tuning.v1.TuningTask tuning_tasks = 1;</code>
     */
    private $tuning_tasks;
    /**
     * Token to retrieve the next page of results.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Yandex\Cloud\Ai\Tuning\V1\TuningTask>|\Google\Protobuf\Internal\RepeatedField $tuning_tasks
     *           List of tuning tasks in the specified folder.
     *     @type string $next_page_token
     *           Token to retrieve the next page of results.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yandex\Cloud\Ai\Tuning\V1\TuningService::initOnce();
        parent::__construct($data);
    }

    /**
     * List of tuning tasks in the specified folder.
     *
     * Generated from protobuf field <code>repeated .yandex.cloud.ai.tuning.v1.TuningTask tuning_tasks = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTuningTasks()
    {
        return $this->tuning_tasks;
    }

    /**
     * List of tuning tasks in the specified folder.
     *
     * Generated from protobuf field <code>repeated .yandex.cloud.ai.tuning.v1.TuningTask tuning_tasks = 1;</code>
     * @param array<\Yandex\Cloud\Ai\Tuning\V1\TuningTask>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTuningTasks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yandex\Cloud\Ai\Tuning\V1\TuningTask::class);
        $this->tuning_tasks = $arr;

        return $this;
    }

    /**
     * Token to retrieve the next page of results.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * Token to retrieve the next page of results.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

