<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_optimizers.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>yandex.cloud.ai.tuning.v1.OptimizerAdamw</code>
 */
class OptimizerAdamw extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double beta1 = 1;</code>
     */
    protected $beta1 = 0.0;
    /**
     * Generated from protobuf field <code>double beta2 = 2;</code>
     */
    protected $beta2 = 0.0;
    /**
     * Generated from protobuf field <code>double eps = 3;</code>
     */
    protected $eps = 0.0;
    /**
     * Generated from protobuf field <code>double weight_decay = 4;</code>
     */
    protected $weight_decay = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $beta1
     *     @type float $beta2
     *     @type float $eps
     *     @type float $weight_decay
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yandex\Cloud\Ai\Tuning\V1\TuningOptimizers::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double beta1 = 1;</code>
     * @return float
     */
    public function getBeta1()
    {
        return $this->beta1;
    }

    /**
     * Generated from protobuf field <code>double beta1 = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setBeta1($var)
    {
        GPBUtil::checkDouble($var);
        $this->beta1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double beta2 = 2;</code>
     * @return float
     */
    public function getBeta2()
    {
        return $this->beta2;
    }

    /**
     * Generated from protobuf field <code>double beta2 = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setBeta2($var)
    {
        GPBUtil::checkDouble($var);
        $this->beta2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double eps = 3;</code>
     * @return float
     */
    public function getEps()
    {
        return $this->eps;
    }

    /**
     * Generated from protobuf field <code>double eps = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setEps($var)
    {
        GPBUtil::checkDouble($var);
        $this->eps = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double weight_decay = 4;</code>
     * @return float
     */
    public function getWeightDecay()
    {
        return $this->weight_decay;
    }

    /**
     * Generated from protobuf field <code>double weight_decay = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setWeightDecay($var)
    {
        GPBUtil::checkDouble($var);
        $this->weight_decay = $var;

        return $this;
    }

}

