<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_schedulers.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>yandex.cloud.ai.tuning.v1.SchedulerLinear</code>
 */
class SchedulerLinear extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double min_lr = 1;</code>
     */
    protected $min_lr = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $min_lr
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yandex\Cloud\Ai\Tuning\V1\TuningSchedulers::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double min_lr = 1;</code>
     * @return float
     */
    public function getMinLr()
    {
        return $this->min_lr;
    }

    /**
     * Generated from protobuf field <code>double min_lr = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setMinLr($var)
    {
        GPBUtil::checkDouble($var);
        $this->min_lr = $var;

        return $this;
    }

}

