<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_service.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>yandex.cloud.ai.tuning.v1.TextEmbeddingTripletParams</code>
 */
class TextEmbeddingTripletParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 seed = 1;</code>
     */
    protected $seed = 0;
    /**
     * Generated from protobuf field <code>double lr = 2;</code>
     */
    protected $lr = 0.0;
    /**
     * Generated from protobuf field <code>int64 n_samples = 3;</code>
     */
    protected $n_samples = 0;
    /**
     * Generated from protobuf field <code>string additional_arguments = 7;</code>
     */
    protected $additional_arguments = '';
    /**
     * Generated from protobuf field <code>repeated int64 embedding_dims = 8;</code>
     */
    private $embedding_dims;
    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TextEmbeddingTripletParams.Scheduler scheduler = 200;</code>
     */
    protected $scheduler = null;
    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TextEmbeddingTripletParams.Optimizer optimizer = 201;</code>
     */
    protected $optimizer = null;
    protected $tuning_type;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $seed
     *     @type float $lr
     *     @type int|string $n_samples
     *     @type string $additional_arguments
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $embedding_dims
     *     @type \Yandex\Cloud\Ai\Tuning\V1\TuningTypeLora $lora
     *     @type \Yandex\Cloud\Ai\Tuning\V1\TuningTypePromptTune $prompt_tune
     *     @type \Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingTripletParams\Scheduler $scheduler
     *     @type \Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingTripletParams\Optimizer $optimizer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yandex\Cloud\Ai\Tuning\V1\TuningService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 seed = 1;</code>
     * @return int|string
     */
    public function getSeed()
    {
        return $this->seed;
    }

    /**
     * Generated from protobuf field <code>int64 seed = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSeed($var)
    {
        GPBUtil::checkInt64($var);
        $this->seed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double lr = 2;</code>
     * @return float
     */
    public function getLr()
    {
        return $this->lr;
    }

    /**
     * Generated from protobuf field <code>double lr = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setLr($var)
    {
        GPBUtil::checkDouble($var);
        $this->lr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 n_samples = 3;</code>
     * @return int|string
     */
    public function getNSamples()
    {
        return $this->n_samples;
    }

    /**
     * Generated from protobuf field <code>int64 n_samples = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNSamples($var)
    {
        GPBUtil::checkInt64($var);
        $this->n_samples = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string additional_arguments = 7;</code>
     * @return string
     */
    public function getAdditionalArguments()
    {
        return $this->additional_arguments;
    }

    /**
     * Generated from protobuf field <code>string additional_arguments = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAdditionalArguments($var)
    {
        GPBUtil::checkString($var, True);
        $this->additional_arguments = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 embedding_dims = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEmbeddingDims()
    {
        return $this->embedding_dims;
    }

    /**
     * Generated from protobuf field <code>repeated int64 embedding_dims = 8;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEmbeddingDims($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->embedding_dims = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTypeLora lora = 100;</code>
     * @return \Yandex\Cloud\Ai\Tuning\V1\TuningTypeLora|null
     */
    public function getLora()
    {
        return $this->readOneof(100);
    }

    public function hasLora()
    {
        return $this->hasOneof(100);
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTypeLora lora = 100;</code>
     * @param \Yandex\Cloud\Ai\Tuning\V1\TuningTypeLora $var
     * @return $this
     */
    public function setLora($var)
    {
        GPBUtil::checkMessage($var, \Yandex\Cloud\Ai\Tuning\V1\TuningTypeLora::class);
        $this->writeOneof(100, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTypePromptTune prompt_tune = 101;</code>
     * @return \Yandex\Cloud\Ai\Tuning\V1\TuningTypePromptTune|null
     */
    public function getPromptTune()
    {
        return $this->readOneof(101);
    }

    public function hasPromptTune()
    {
        return $this->hasOneof(101);
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTypePromptTune prompt_tune = 101;</code>
     * @param \Yandex\Cloud\Ai\Tuning\V1\TuningTypePromptTune $var
     * @return $this
     */
    public function setPromptTune($var)
    {
        GPBUtil::checkMessage($var, \Yandex\Cloud\Ai\Tuning\V1\TuningTypePromptTune::class);
        $this->writeOneof(101, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TextEmbeddingTripletParams.Scheduler scheduler = 200;</code>
     * @return \Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingTripletParams\Scheduler|null
     */
    public function getScheduler()
    {
        return $this->scheduler;
    }

    public function hasScheduler()
    {
        return isset($this->scheduler);
    }

    public function clearScheduler()
    {
        unset($this->scheduler);
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TextEmbeddingTripletParams.Scheduler scheduler = 200;</code>
     * @param \Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingTripletParams\Scheduler $var
     * @return $this
     */
    public function setScheduler($var)
    {
        GPBUtil::checkMessage($var, \Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingTripletParams\Scheduler::class);
        $this->scheduler = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TextEmbeddingTripletParams.Optimizer optimizer = 201;</code>
     * @return \Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingTripletParams\Optimizer|null
     */
    public function getOptimizer()
    {
        return $this->optimizer;
    }

    public function hasOptimizer()
    {
        return isset($this->optimizer);
    }

    public function clearOptimizer()
    {
        unset($this->optimizer);
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TextEmbeddingTripletParams.Optimizer optimizer = 201;</code>
     * @param \Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingTripletParams\Optimizer $var
     * @return $this
     */
    public function setOptimizer($var)
    {
        GPBUtil::checkMessage($var, \Yandex\Cloud\Ai\Tuning\V1\TextEmbeddingTripletParams\Optimizer::class);
        $this->optimizer = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getTuningType()
    {
        return $this->whichOneof("tuning_type");
    }

}

