<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_service.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

if (false) {
    /**
     * This class is deprecated. Use Yandex\Cloud\Ai\Tuning\V1\TextToTextCompletionTuningParams\Scheduler instead.
     * @deprecated
     */
    class TextToTextCompletionTuningParams_Scheduler {}
}
class_exists(TextToTextCompletionTuningParams\Scheduler::class);
@trigger_error('Yandex\Cloud\Ai\Tuning\V1\TextToTextCompletionTuningParams_Scheduler is deprecated and will be removed in the next major release. Use Yandex\Cloud\Ai\Tuning\V1\TextToTextCompletionTuningParams\Scheduler instead', E_USER_DEPRECATED);

