<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_service.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

if (false) {
    /**
     * This class is deprecated. Use Yandex\Cloud\Ai\Tuning\V1\TextToTextCompletionTuningParams\Optimizer instead.
     * @deprecated
     */
    class TextToTextCompletionTuningParams_Optimizer {}
}
class_exists(TextToTextCompletionTuningParams\Optimizer::class);
@trigger_error('Yandex\Cloud\Ai\Tuning\V1\TextToTextCompletionTuningParams_Optimizer is deprecated and will be removed in the next major release. Use Yandex\Cloud\Ai\Tuning\V1\TextToTextCompletionTuningParams\Optimizer instead', E_USER_DEPRECATED);

