<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_types.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>yandex.cloud.ai.tuning.v1.TuningTypePromptTune</code>
 */
class TuningTypePromptTune extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 virtual_tokens = 1;</code>
     */
    protected $virtual_tokens = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $virtual_tokens
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yandex\Cloud\Ai\Tuning\V1\TuningTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 virtual_tokens = 1;</code>
     * @return int|string
     */
    public function getVirtualTokens()
    {
        return $this->virtual_tokens;
    }

    /**
     * Generated from protobuf field <code>int64 virtual_tokens = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVirtualTokens($var)
    {
        GPBUtil::checkInt64($var);
        $this->virtual_tokens = $var;

        return $this;
    }

}

