<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_task.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

if (false) {
    /**
     * This class is deprecated. Use Yandex\Cloud\Ai\Tuning\V1\TuningTask\Status instead.
     * @deprecated
     */
    class TuningTask_Status {}
}
class_exists(TuningTask\Status::class);
@trigger_error('Yandex\Cloud\Ai\Tuning\V1\TuningTask_Status is deprecated and will be removed in the next major release. Use Yandex\Cloud\Ai\Tuning\V1\TuningTask\Status instead', E_USER_DEPRECATED);

