<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_service.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>yandex.cloud.ai.tuning.v1.TuningResponse</code>
 */
class TuningResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tuning_task_id = 3;</code>
     */
    protected $tuning_task_id = '';
    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTask.Status status = 4;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string target_model_uri = 5;</code>
     */
    protected $target_model_uri = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tuning_task_id
     *     @type int $status
     *     @type string $target_model_uri
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yandex\Cloud\Ai\Tuning\V1\TuningService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tuning_task_id = 3;</code>
     * @return string
     */
    public function getTuningTaskId()
    {
        return $this->tuning_task_id;
    }

    /**
     * Generated from protobuf field <code>string tuning_task_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTuningTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tuning_task_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTask.Status status = 4;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTask.Status status = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Yandex\Cloud\Ai\Tuning\V1\TuningTask\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_model_uri = 5;</code>
     * @return string
     */
    public function getTargetModelUri()
    {
        return $this->target_model_uri;
    }

    /**
     * Generated from protobuf field <code>string target_model_uri = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetModelUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_model_uri = $var;

        return $this;
    }

}

