<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_service.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

if (false) {
    /**
     * This class is deprecated. Use Yandex\Cloud\Ai\Tuning\V1\TuningRequest\WeightedDataset instead.
     * @deprecated
     */
    class TuningRequest_WeightedDataset {}
}
class_exists(TuningRequest\WeightedDataset::class);
@trigger_error('Yandex\Cloud\Ai\Tuning\V1\TuningRequest_WeightedDataset is deprecated and will be removed in the next major release. Use Yandex\Cloud\Ai\Tuning\V1\TuningRequest\WeightedDataset instead', E_USER_DEPRECATED);

