<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_error.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>yandex.cloud.ai.tuning.v1.TuningError</code>
 */
class TuningError extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tuning_task_id = 1;</code>
     */
    protected $tuning_task_id = '';
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningError.Type type = 3;</code>
     */
    protected $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tuning_task_id
     *     @type string $message
     *     @type int $type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yandex\Cloud\Ai\Tuning\V1\TuningError::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tuning_task_id = 1;</code>
     * @return string
     */
    public function getTuningTaskId()
    {
        return $this->tuning_task_id;
    }

    /**
     * Generated from protobuf field <code>string tuning_task_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTuningTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tuning_task_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningError.Type type = 3;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningError.Type type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Yandex\Cloud\Ai\Tuning\V1\TuningError\Type::class);
        $this->type = $var;

        return $this;
    }

}

