<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_error.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

if (false) {
    /**
     * This class is deprecated. Use Yandex\Cloud\Ai\Tuning\V1\TuningError\Type instead.
     * @deprecated
     */
    class TuningError_Type {}
}
class_exists(TuningError\Type::class);
@trigger_error('Yandex\Cloud\Ai\Tuning\V1\TuningError_Type is deprecated and will be removed in the next major release. Use Yandex\Cloud\Ai\Tuning\V1\TuningError\Type instead', E_USER_DEPRECATED);

