<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_types.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>yandex.cloud.ai.tuning.v1.TuningTypeLora</code>
 */
class TuningTypeLora extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 rank = 1;</code>
     */
    protected $rank = 0;
    /**
     * Integer value
     *
     * Generated from protobuf field <code>double alpha = 2;</code>
     */
    protected $alpha = 0.0;
    /**
     * Generated from protobuf field <code>string initialization = 3;</code>
     */
    protected $initialization = '';
    /**
     * Generated from protobuf field <code>string type = 4;</code>
     */
    protected $type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $rank
     *     @type float $alpha
     *           Integer value
     *     @type string $initialization
     *     @type string $type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yandex\Cloud\Ai\Tuning\V1\TuningTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 rank = 1;</code>
     * @return int|string
     */
    public function getRank()
    {
        return $this->rank;
    }

    /**
     * Generated from protobuf field <code>int64 rank = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRank($var)
    {
        GPBUtil::checkInt64($var);
        $this->rank = $var;

        return $this;
    }

    /**
     * Integer value
     *
     * Generated from protobuf field <code>double alpha = 2;</code>
     * @return float
     */
    public function getAlpha()
    {
        return $this->alpha;
    }

    /**
     * Integer value
     *
     * Generated from protobuf field <code>double alpha = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setAlpha($var)
    {
        GPBUtil::checkDouble($var);
        $this->alpha = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string initialization = 3;</code>
     * @return string
     */
    public function getInitialization()
    {
        return $this->initialization;
    }

    /**
     * Generated from protobuf field <code>string initialization = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setInitialization($var)
    {
        GPBUtil::checkString($var, True);
        $this->initialization = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 4;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

}

