<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_service.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>yandex.cloud.ai.tuning.v1.TuningMetadata</code>
 */
class TuningMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tuning_task_id = 1;</code>
     */
    protected $tuning_task_id = '';
    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTask.Status status = 2;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>int64 total_steps = 3;</code>
     */
    protected $total_steps = 0;
    /**
     * Generated from protobuf field <code>int64 current_step = 4;</code>
     */
    protected $current_step = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tuning_task_id
     *     @type int $status
     *     @type int|string $total_steps
     *     @type int|string $current_step
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yandex\Cloud\Ai\Tuning\V1\TuningService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tuning_task_id = 1;</code>
     * @return string
     */
    public function getTuningTaskId()
    {
        return $this->tuning_task_id;
    }

    /**
     * Generated from protobuf field <code>string tuning_task_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTuningTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tuning_task_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTask.Status status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTask.Status status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Yandex\Cloud\Ai\Tuning\V1\TuningTask\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total_steps = 3;</code>
     * @return int|string
     */
    public function getTotalSteps()
    {
        return $this->total_steps;
    }

    /**
     * Generated from protobuf field <code>int64 total_steps = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalSteps($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_steps = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 current_step = 4;</code>
     * @return int|string
     */
    public function getCurrentStep()
    {
        return $this->current_step;
    }

    /**
     * Generated from protobuf field <code>int64 current_step = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCurrentStep($var)
    {
        GPBUtil::checkInt64($var);
        $this->current_step = $var;

        return $this;
    }

}

