<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_task.proto

namespace Yandex\Cloud\Ai\Tuning\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>yandex.cloud.ai.tuning.v1.TuningTask</code>
 */
class TuningTask extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string task_id = 1;</code>
     */
    protected $task_id = '';
    /**
     * Generated from protobuf field <code>string operation_id = 3;</code>
     */
    protected $operation_id = '';
    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTask.Status status = 4;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string folder_id = 5;</code>
     */
    protected $folder_id = '';
    /**
     * Generated from protobuf field <code>string created_by = 6;</code>
     */
    protected $created_by = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7;</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 8;</code>
     */
    protected $started_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp finished_at = 9;</code>
     */
    protected $finished_at = null;
    /**
     * Generated from protobuf field <code>string source_model_uri = 10;</code>
     */
    protected $source_model_uri = '';
    /**
     * Generated from protobuf field <code>string target_model_uri = 11;</code>
     */
    protected $target_model_uri = '';
    /**
     * Generated from protobuf field <code>string name = 12 [(.yandex.cloud.pattern) = "^[A-Za-z0-9 _-]{3,100}$"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string description = 13;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>map<string, string> labels = 14;</code>
     */
    private $labels;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $task_id
     *     @type string $operation_id
     *     @type int $status
     *     @type string $folder_id
     *     @type string $created_by
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $started_at
     *     @type \Google\Protobuf\Timestamp $finished_at
     *     @type string $source_model_uri
     *     @type string $target_model_uri
     *     @type string $name
     *     @type string $description
     *     @type array|\Google\Protobuf\Internal\MapField $labels
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Yandex\Cloud\Ai\Tuning\V1\TuningTask::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string task_id = 1;</code>
     * @return string
     */
    public function getTaskId()
    {
        return $this->task_id;
    }

    /**
     * Generated from protobuf field <code>string task_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->task_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string operation_id = 3;</code>
     * @return string
     */
    public function getOperationId()
    {
        return $this->operation_id;
    }

    /**
     * Generated from protobuf field <code>string operation_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOperationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->operation_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTask.Status status = 4;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.yandex.cloud.ai.tuning.v1.TuningTask.Status status = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Yandex\Cloud\Ai\Tuning\V1\TuningTask\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string folder_id = 5;</code>
     * @return string
     */
    public function getFolderId()
    {
        return $this->folder_id;
    }

    /**
     * Generated from protobuf field <code>string folder_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFolderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->folder_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_by = 6;</code>
     * @return string
     */
    public function getCreatedBy()
    {
        return $this->created_by;
    }

    /**
     * Generated from protobuf field <code>string created_by = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedBy($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 8;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getStartedAt()
    {
        return $this->started_at;
    }

    public function hasStartedAt()
    {
        return isset($this->started_at);
    }

    public function clearStartedAt()
    {
        unset($this->started_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 8;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->started_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp finished_at = 9;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getFinishedAt()
    {
        return $this->finished_at;
    }

    public function hasFinishedAt()
    {
        return isset($this->finished_at);
    }

    public function clearFinishedAt()
    {
        unset($this->finished_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp finished_at = 9;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setFinishedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->finished_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source_model_uri = 10;</code>
     * @return string
     */
    public function getSourceModelUri()
    {
        return $this->source_model_uri;
    }

    /**
     * Generated from protobuf field <code>string source_model_uri = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceModelUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_model_uri = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_model_uri = 11;</code>
     * @return string
     */
    public function getTargetModelUri()
    {
        return $this->target_model_uri;
    }

    /**
     * Generated from protobuf field <code>string target_model_uri = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetModelUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_model_uri = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 12 [(.yandex.cloud.pattern) = "^[A-Za-z0-9 _-]{3,100}$"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 12 [(.yandex.cloud.pattern) = "^[A-Za-z0-9 _-]{3,100}$"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 13;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> labels = 14;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getLabels()
    {
        return $this->labels;
    }

    /**
     * Generated from protobuf field <code>map<string, string> labels = 14;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setLabels($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->labels = $arr;

        return $this;
    }

}

