<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/ai/tuning/v1/tuning_optimizers.proto

namespace GPBMetadata\Yandex\Cloud\Ai\Tuning\V1;

class TuningOptimizers
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ž
1yandex/cloud/ai/tuning/v1/tuning_optimizers.protoyandex.cloud.ai.tuning.v1"Q
OptimizerAdamw
beta1 (
beta2 (
eps (
weight_decay (Bc
yandex.cloud.api.ai.tuning.v1ZBgithub.com/yandex-cloud/go-genproto/yandex/cloud/ai/tuning/v1;fomobproto3'
        , true);

        static::$is_initialized = true;
    }
}

